spring.application.name=flipkart-backend

spring.data.mongodb.uri=mongodb+srv://sowmya0410k:sowmya04102005@cluster0.bfjurqt.mongodb.net/flipkart?appName=Cluster0
spring.data.mongodb.database=flipkart

server.port=${PORT:8081}

jwt.secret=S5YJ4L/Um6VfnLoa43uxl0oir8pmRKYTUdDN1kY7zQI= 
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html

spring.security.oauth2.client.registration.google.client-id=902742571861-sjpsi3s2h6hhd6jc8rou1mqndh6tb9k7.apps.googleusercontent.com
